// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_auth_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContestSubmission = {
    expected_answers: Array<ExpectedAnswer>;
    user_inputs: Array<UserInput>;
};

export type Definition = {
    name: string;
    description: string;
    tasks: Array<Task>;
};

export type DefinitionORM = {
    id: number;
    name: string;
    description: string;
};

export type ExpectedAnswer = {
    task_id: number;
    expected_answer: unknown;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Task = {
    id: number;
    type: TaskType;
    autograde?: boolean;
};

export type TaskEvalStatus = 'SUCCESS' | 'PENDING' | 'SKIPPED' | 'FAILED';

export type TaskResultORM = {
    id: number;
    submission_id: number;
    definition_id: number;
    task_id: number;
    started_at: string;
    completed_at: (string | null);
    job_id: (string | null);
    status: TaskEvalStatus;
    result?: {
        [key: string]: unknown;
    };
    error: (string | null);
};

export type TaskType = 'MULTIPLE_CHOICE_TASK' | 'MULTIPLE_RESPONSE_TASK' | 'SHORT_ANSWER_TASK' | 'PROGRAMMING_TASK';

export type Token = {
    access_token: string;
    token_type: string;
    user: UserPublic;
};

export type UserInput = {
    task_id: number;
    user_input: unknown;
};

export type UserPublic = {
    id: number;
    username: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginData = {
    body: Body_login_auth_token_post;
};

export type LoginResponse = (Token);

export type LoginError = (HTTPValidationError);

export type LogoutResponse = (unknown);

export type LogoutError = unknown;

export type GetUserData = unknown;

export type GetUserResponse = (UserPublic);

export type GetUserError = (HTTPValidationError);

export type GetDefinitionsData = unknown;

export type GetDefinitionsResponse = (Array<DefinitionORM>);

export type GetDefinitionsError = (HTTPValidationError);

export type SubmitDefinitionData = {
    body: Definition;
};

export type SubmitDefinitionResponse = (DefinitionORM);

export type SubmitDefinitionError = (HTTPValidationError);

export type GetDefinitionData = {
    path: {
        id: number;
    };
};

export type GetDefinitionResponse = (Definition);

export type GetDefinitionError = (HTTPValidationError);

export type UpdateDefinitionData = {
    body: Definition;
    path: {
        id: number;
    };
};

export type UpdateDefinitionResponse = (DefinitionORM);

export type UpdateDefinitionError = (HTTPValidationError);

export type SubmitContestSubmissionData = {
    body: ContestSubmission;
    path: {
        id: number;
    };
    query?: {
        task_id?: (number | null);
    };
};

export type SubmitContestSubmissionResponse = (Array<TaskResultORM>);

export type SubmitContestSubmissionError = (HTTPValidationError);

export type GetSubmissionData = {
    path: {
        submission_id: number;
    };
    query?: {
        task_id?: (number | null);
    };
};

export type GetSubmissionResponse = (Array<TaskResultORM>);

export type GetSubmissionError = (HTTPValidationError);