// This file is auto-generated by @hey-api/openapi-ts

export type BaseDefinitionDTO = {
    id: number;
    name: string;
    description: string;
};

export type Body_login_auth_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContestSubmission = {
    expected_answers: RootModelList_ExpectedAnswer_;
    user_inputs: RootModelList_UserInput_;
};

export type Definition = {
    name: string;
    description: string;
    tasks: Array<Task>;
};

export type ExpectedAnswer = {
    task_id: number;
    expected_answer: unknown;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type RootModelList_ExpectedAnswer_ = Array<ExpectedAnswer>;

export type RootModelList_UserInput_ = Array<UserInput>;

export type Task = {
    id: number;
    type: TaskType;
    autograde?: boolean;
};

export type TaskType = 'MULTIPLE_CHOICE_TASK' | 'MULTIPLE_RESPONSE_TASK' | 'SHORT_ANSWER_TASK' | 'PROGRAMMING_TASK';

export type Token = {
    access_token: string;
    token_type: string;
    user: UserPublic;
};

export type UserInput = {
    task_id: number;
    user_input: unknown;
};

export type UserPublic = {
    id: number;
    username: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginAuthTokenPostData = {
    body: Body_login_auth_token_post;
};

export type LoginAuthTokenPostResponse = (Token);

export type LoginAuthTokenPostError = (HTTPValidationError);

export type LogoutAuthLogoutGetResponse = (unknown);

export type LogoutAuthLogoutGetError = unknown;

export type GetUserAuthSessionGetData = unknown;

export type GetUserAuthSessionGetResponse = (UserPublic);

export type GetUserAuthSessionGetError = (HTTPValidationError);

export type GetDefinitionsContestsDefinitionsGetData = unknown;

export type GetDefinitionsContestsDefinitionsGetResponse = (Array<BaseDefinitionDTO>);

export type GetDefinitionsContestsDefinitionsGetError = (HTTPValidationError);

export type SubmitDefinitionContestsDefinitionsPostData = {
    body: Definition;
};

export type SubmitDefinitionContestsDefinitionsPostResponse = (unknown);

export type SubmitDefinitionContestsDefinitionsPostError = (HTTPValidationError);

export type UpdateDefinitionContestsDefinitionsIdPatchData = {
    body: Definition;
    path: {
        id: number;
    };
};

export type UpdateDefinitionContestsDefinitionsIdPatchResponse = (unknown);

export type UpdateDefinitionContestsDefinitionsIdPatchError = (HTTPValidationError);

export type SubmitContestSubmissionContestsDefinitionsIdSubmissionsPostData = {
    body: ContestSubmission;
    path: {
        id: number;
    };
    query?: {
        task_id?: (number | null);
    };
};

export type SubmitContestSubmissionContestsDefinitionsIdSubmissionsPostResponse = (unknown);

export type SubmitContestSubmissionContestsDefinitionsIdSubmissionsPostError = (HTTPValidationError);

export type GetSubmissionContestsSubmissionsSubmissionIdGetData = {
    path: {
        submission_id: number;
    };
    query?: {
        task_id?: (number | null);
    };
};

export type GetSubmissionContestsSubmissionsSubmissionIdGetResponse = (unknown);

export type GetSubmissionContestsSubmissionsSubmissionIdGetError = (HTTPValidationError);